//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackWalkLicenta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rezervare
    {
        public int RezervareId { get; set; }
        [Required]
        [Display(Name = "Adresa de ridicare")]
        public string Adresa_de_Ridicare { get; set; }
        [Required]
        [Display(Name = "Telefonul expeditorului")]
        public string Numarul_persoanei_care_trimite { get; set; }
        [Required]
        [Display(Name = "Adresa de predare")]
        public string Adresa_de_Predare { get; set; }
        [Required]
        [Display(Name = "Telefonul destinatarului")]
        public string Numarul_persoanei_care_primeste { get; set; }
        [Required]
        [Display(Name = "Greutatea aproximativă")]
        public string Cantitate_aproximativa { get; set; }
        [Required]
        //[DataType(DataType.Date)]
        [Display(Name="Data trimiterii")]
        public Nullable<System.DateTime> Data_Trimiterii { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
